BASE_PATH=.
INFRA_PATH=$(BASE_PATH)/biz/infra
CONFIG_PATH=$(BASE_PATH)/config
CONFIG_PROTOC_OUT=$(CONFIG_PATH)/gen
PROTO_GOGO=github.com/gogo/protobuf@v1.3.2
PROTO_GOGO_PATH=$(GOPATH)/pkg/mod/$(PROTO_GOGO)

.PHONY: init
init:
	if [ "$(which wire)" == "" ]; then go get -u github.com/google/wire/cmd/wire; fi
	if [ "$(which mb)" == "" ]; then go get -u github.com/maliboot/mago/mali; fi
	if [ "$(which protoc-gen-gofast)" == "" ]; then go install $(PROTO_GOGO); fi

.PHONY: wire
wire: wire_inject wire_do
wire_inject:
	mali inject
wire_do:
	wire $(BASE_PATH)

.PHONY: config
config: pre_config do_config
pre_config:
	rm -rf $(CONFIG_PROTOC_OUT) && mkdir -p $(CONFIG_PROTOC_OUT)
do_config:
	protoc --gofast_opt=paths=source_relative \
	       --gofast_out=$(CONFIG_PROTOC_OUT) \
	       -I $(CONFIG_PATH) \
	       -I $(PROTO_GOGO_PATH) \
	       config.proto

.PHONY: clean
clean:
	@echo "be done."
